[package]
name = "nostr-sdk"
version = "0.22.0-bitcoin-v0.29"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "rust"]

[features]
default = ["all-nips"]
blocking = ["dep:once_cell", "async-utility/blocking", "nostr/blocking"]
vanity = ["nostr/vanity"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip19", "nip46", "nip47"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip19 = ["nostr/nip19"]
nip46 = ["nostr/nip46"]
nip47 = ["nostr/nip47"]

[dependencies]
async-utility = "0.1"
nostr = { version = "0.22.0-bitcoin-v0.29", path = "../nostr", default-features = false }
nostr-sdk-net = { version = "0.22", path = "../nostr-sdk-net" }
once_cell = { version = "1.17", optional = true }
thiserror = "1.0"
tracing = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "time", "macros", "sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "macros", "sync"] }

[dev-dependencies]
serde_json = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "client-with-opts"
required-features = ["all-nips"]

[[example]]
name = "blocking"
required-features = ["all-nips", "blocking"]

[[example]]
name = "nostr-connect"
required-features = ["nip46"]

[[example]]
name = "bot"
required-features = ["all-nips"]

[[example]]
name = "client-stop"
required-features = ["all-nips"]

[[example]]
name = "shutdown-on-drop"

[[example]]
name = "subscriptions"
required-features = ["all-nips"]

[[example]]
name = "wait-for-ok"
required-features = ["nip19"]