[package]
name = "nostr-sdk"
version = "0.20.1"
edition = "2021"
description = "High level Nostr client library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "rust"]

[features]
default = ["all-nips"]
sqlite = ["dep:nostr-sdk-sqlite"]
blocking = ["dep:once_cell", "nostr/blocking"]
vanity = ["nostr/vanity"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip19", "nip46"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip19 = ["nostr/nip19"]
nip46 = ["nostr/nip46"]

[dependencies]
async-stream = "0.3"
log = "0.4"
nostr = { version = "0.20", path = "../nostr", default-features = false }
nostr-sdk-net = { version = "0.20", path = "../nostr-sdk-net" }
nostr-sdk-sqlite = { version = "0.20", path = "../nostr-sdk-sqlite", optional = true }
once_cell = { version = "1.17", optional = true }
thiserror = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.26", default-features = false, features = ["rt-multi-thread", "time", "macros", "sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.2", features = ["futures"] }
tokio = { version = "1.26", default-features = false, features = ["rt", "macros", "sync"] }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
env_logger = "0.10"
serde_json = "1.0"

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "client_with_opts"
required-features = ["all-nips"]

[[example]]
name = "sqlite"
required-features = ["all-nips", "sqlite"]

[[example]]
name = "blocking"
required-features = ["all-nips", "blocking"]

[[example]]
name = "nostr_connect"
required-features = ["nip46"]