[package]
name = "nostr-sdk"
version = "0.36.0"
edition = "2021"
description = "High level Nostr client library."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
tor = ["nostr-relay-pool/tor"]
lmdb = ["dep:nostr-lmdb"]
ndb = ["dep:nostr-ndb"]
indexeddb = ["dep:nostr-indexeddb"]
webln = ["nip57", "nostr-zapper?/webln"]
all-nips = ["nip04", "nip05", "nip06", "nip07", "nip11", "nip44", "nip47", "nip49", "nip57", "nip59"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip07 = ["nostr/nip07"]
nip11 = ["nostr/nip11", "nostr-relay-pool/nip11"]
nip44 = ["nostr/nip44"]
nip47 = ["nostr/nip47", "dep:nwc"]
nip49 = ["nostr/nip49"]
nip57 = ["nostr/nip57", "dep:nostr-zapper", "dep:lnurl-pay"]
nip59 = ["nostr/nip59"]

[dependencies]
async-utility.workspace = true
atomic-destructor.workspace = true
lnurl-pay = { version = "0.6", features = ["api"], optional = true }
nostr = { workspace = true, features = ["std"] }
nostr-database.workspace = true
nostr-relay-pool.workspace = true
nostr-zapper = { workspace = true, optional = true }
nwc = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["std", "attributes"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nostr-lmdb = { workspace = true, optional = true }
nostr-ndb = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
nostr-indexeddb = { workspace = true, optional = true }

[dev-dependencies]
nostr-connect.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[example]]
name = "aggregated-query"
required-features = ["all-nips", "lmdb"]

[[example]]
name = "blacklist"
required-features = ["all-nips"]

[[example]]
name = "client-with-opts"
required-features = ["all-nips"]

[[example]]
name = "client"
required-features = ["all-nips"]

[[example]]
name = "fetch-events"
required-features = ["all-nips"]

[[example]]
name = "gossip"
required-features = ["all-nips"]

[[example]]
name = "nostr-connect"
required-features = ["nip59"]

[[example]]
name = "bot"
required-features = ["all-nips"]

[[example]]
name = "nostrdb"
required-features = ["all-nips", "ndb"]

[[example]]
name = "shutdown-on-drop"

[[example]]
name = "stream-events"
required-features = ["all-nips"]

[[example]]
name = "subscriptions"
required-features = ["all-nips"]

[[example]]
name = "switch-account"

[[example]]
name = "tor"
required-features = ["all-nips", "tor"]

[[example]]
name = "lmdb"
required-features = ["all-nips", "lmdb"]

[[example]]
name = "negentropy"
required-features = ["all-nips", "lmdb"]

[[example]]
name = "nip47"
required-features = ["nip47"]

[[example]]
name = "nip65"

[[example]]
name = "whitelist"

[[example]]
name = "zapper"
required-features = ["nip47", "nip57"]
