[package]
name = "nostr-lmdb"
version = "0.36.0"
edition = "2021"
description = "LMDB storage backend for nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "database", "lmdb"]

[dependencies]
heed = { version = "0.20", default-features = false, features = ["read-txn-no-tls"] }
nostr = { workspace = true, features = ["std"] }
nostr-database = { workspace = true, features = ["flatbuf"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tracing = { workspace = true, features = ["std", "attributes"] }

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros"] }
