[package]
name = "nwc"
version = "0.36.0"
edition = "2021"
description = "NWC client and zapper backend for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "zapper", "nwc"]

[features]
default = []
tor = ["nostr-relay-pool/tor"]

[dependencies]
async-trait.workspace = true
async-utility.workspace = true
nostr = { workspace = true, features = ["std", "nip47"] }
nostr-relay-pool.workspace = true
nostr-zapper.workspace = true
thiserror.workspace = true
tracing = { workspace = true, features = ["std"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber.workspace = true
