name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: make && make more && make check-fmt

  check-crates:
    name: Check crates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: make check-crates

  check-crates-msrv:
    name: Check crates (MSRV)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: make check-crates-msrv

  check-bindings:
    name: Check bindings
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: make check-bindings

  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: make check-docs

  build-no-std:
    name: Build no_std
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/nostr/examples/embedded
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set default toolchain
      run: rustup default nightly
    - name: Set profile
      run: rustup set profile minimal
    - name: Init
      run: sudo apt update && make init
    - name: Build
      run: make
