name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: bash contrib/scripts/check-fmt.sh check

  check-crates:
    name: Check crates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: bash contrib/scripts/check-crates.sh "" ci

  check-crates-msrv:
    name: Check crates (MSRV)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: bash contrib/scripts/check-crates.sh msrv ci

  check-bindings:
    name: Check bindings
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: bash contrib/scripts/check-bindings.sh

  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: bash contrib/scripts/check-docs.sh

  build-no-std:
    name: Build no_std
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/nostr/examples/embedded
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set default toolchain
      run: rustup default nightly
    - name: Set profile
      run: rustup set profile minimal
    - name: Install just
      run: cargo install just
    - name: Init
      run: sudo apt update && just init
    - name: Build
      run: just build